<a href="https://colab.research.google.com/github/SINUVMATHEW/ineedtolearn/blob/learn_py/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np

x = np.random.randint(100, size=(3,3))
print(x)

y = np.random.randint(100, size=(3,3))
print(y)

p = np.dot(x,y)
print(p)

[[11 36 90]
 [21 52 51]
 [52 46  3]]
[[ 2 37 33]
 [35 22 92]
 [54 33 99]]
[[ 6142  4169 12585]
 [ 4616  3604 10526]
 [ 1876  3035  6245]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.
import numpy as np

a =  [55,25,15], [30,44,2], [11,45,77]
arr = np.array(a)
print(arr)

dot = np.linalg.det(arr)
print(int(dot))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180
