<a href="https://colab.research.google.com/github/SINUVMATHEW/ineedtolearn/blob/learn_py/TASK_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For the given ndarray b below, evaluate whether elements in array, b are equal to 'red'.Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [9]:
#please type your answer below this line.
import numpy as np

b = np.array(["blue", "blue", "red", "blue"])
arr = []
for i in range(len(b)):
  if b[i] == "red":
    arr = np.append(arr, i)
print(arr)

[2.]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [7]:
#please type your answer below this line.
import numpy as np
ara1=np.arange(0,6)
ara2=np.arange(6,11)
print(ara1)
print(ara2)
arr = np.append(ara1, ara2)
print(f" array: {arr} ")


[0 1 2 3 4 5]
[ 6  7  8  9 10]
 array: [ 0  1  2  3  4  5  6  7  8  9 10] 


3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [8]:
#please type your answer below this line.
import numpy as np

arr1 = np.arange(0,8).reshape(2,4)
arr2 = np.arange(8,16).reshape(2,4)

print(f"appended at axis 0: {np.append(arr1, arr2, axis=0)}")
print(f"appended at axis 1: {np.append(arr1, arr2, axis=1)}")

appended at axis 0: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
appended at axis 1: [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
