<a href="https://colab.research.google.com/github/SINUVMATHEW/ineedtolearn/blob/learn_py/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [3]:
#please provide your answer below this line.

import random

a = []
b = [0,0,0]

for i in range(0, 3):
  for i in range(0,3):
    b[i] = random.randint(0,20)
  a.append(b)
print(a)

[[7, 19, 7], [7, 19, 7], [7, 19, 7]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [10]:
#please provide your answer below this line.
import numpy as np

a = np.random.rand(4,4)
print(a)

print("Vertical stack")
print(np.vstack(a))

print("Horizontal stack")
print(np.hstack(a))

[[0.54307121 0.27985836 0.07927749 0.63191294]
 [0.01792412 0.24401375 0.16123824 0.4807824 ]
 [0.64728963 0.21042982 0.67613586 0.28639866]
 [0.27071199 0.57909781 0.358685   0.59162147]]
Vertical stack
[[0.54307121 0.27985836 0.07927749 0.63191294]
 [0.01792412 0.24401375 0.16123824 0.4807824 ]
 [0.64728963 0.21042982 0.67613586 0.28639866]
 [0.27071199 0.57909781 0.358685   0.59162147]]
Horizontal stack
[0.54307121 0.27985836 0.07927749 0.63191294 0.01792412 0.24401375
 0.16123824 0.4807824  0.64728963 0.21042982 0.67613586 0.28639866
 0.27071199 0.57909781 0.358685   0.59162147]
